global:
  scrape_interval: 5s
scrape_configs:
  - job_name: fraud-api
    static_configs:
      - targets: ['host.docker.internal:8000']
  - job_name: fraud-worker
    static_configs:
      - targets: ['host.docker.internal:9101']
  - job_name: fraud-history
    static_configs:
      - targets: ['host.docker.internal:9102']
